name: Deploy to S3

on:
  push:
    branches:
      - main  # Auto deploys on push to main
  workflow_dispatch:  # Allows manual deployment from any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # ✅ Get Current Branch Name
      - name: Get Branch Name
        id: branch
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      # ✅ Get Version from VERSION File
      - name: Read Version
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '[:space:]')  # Remove spaces/newlines
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # ✅ Configure AWS Credentials (Stored as GitHub Secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ✅ Sync Repository Files to S3 Using Versioning and Branch
      - name: Upload to S3
        run: |
          S3_BUCKET="neethithevan.com"
          S3_DESTINATION_PATH="V${{ env.VERSION }}"

          echo "🚀 Deploying files to s3://$S3_BUCKET/"
          aws s3 sync . s3://$S3_BUCKET/ --exclude ".git/*" --delete
